### ISSUE TITLE
Readme file please

### ISSUE THREAD

**Issue by rupakraj** [foss-np/elibrary-IMS#1]
Hello! Its nice to see elibrary project initiation here :+1: . I am expecting bit more about the project in readme. Also I tried to run this on my machine and realized there is database script missing.
Could you please provide bit more if this repo is landed here seeking contributions .

![selection_049](https://cloud.githubusercontent.com/assets/1549123/13387422/6946d3e6-dede-11e5-99e3-f749049fdf4b.png)

Thanks

**Comment by samundra** [comment]
Found SQL script in e6c4f97bad267aa8a142cc3440c4ddaa12757c93 commit. SQL script can be found at [SQL_Link](https://github.com/foss-np/elibrary-IMS/blob/e6c4f97bad267aa8a142cc3440c4ddaa12757c93/elims.sql), I Implemented the script and got to User Interface. 

Here I got another error **Table 'db_elms.districtdr' doesn't exist**.

See Screenshot Below: 
![Table Missing](http://i76.photobucket.com/albums/j5/alexshr/elims_error_1_zpsrydtoq1p.jpg)

**Comment by rupakraj** [comment]
@samundra still [this script](https://github.com/foss-np/elibrary-IMS/blob/e6c4f97bad267aa8a142cc3440c4ddaa12757c93/elims.sql) does not seems to be complete since **districtdr** table is missing( as your screen short shows.)  :(

**Comment by krazedkrish** [comment]
:+1:  +1 for project initiation. -0.1 for no ReadMe file. :smile:

**Comment by samundra** [comment]
I have personally emailed the project initiator and have asked him if he would be able to push missing information. Lets wait.

**Comment by prabinraz** [comment]
There was no readme so I need to create one. This project was done my 2
students from KU - 2 years back under my supervision and is still
incomplete. Sql in there was outdated. I will upload the latest one in some
time.

Thanks for concern guys.

Openthito

**Comment by prabinraz** [comment]
Readme file added. we will be adding more info as required

**Comment by samundra** [comment]
I have added installation instruction in readme.
