### ISSUE TITLE
Missing DB Tables, too many hardcoded SQL scripts

### ISSUE THREAD

**Issue by samundra** [foss-np/elibrary-IMS#2]
## Project Code Review/Feedback

During code review, I found following issues in this project.
- Table references (scripts) are missing from the SQL script.
- `index.php` refers to **site_maps**

``` php
mysql_query("SELECT * FROM site_maps WHERE district='$district1'")
```
- [mysql_query](http://php.net/manual/en/function.mysql-query.php) is deprecated and there are tons of usage of [mysql_query](http://php.net/manual/en/function.mysql-query.php) throughout the code
- Usage of Raw SQL queries
- Missing SQL injection prevention though few places have it.
## Suggestions:
- It's good to see such projects coming into the `foss-np` github repo.
- Standard wise I would suggest we wait and discuss on the group before having any projects in the community repository. 
- At least have some standard, guidelines on projects before we push them to the repository.

These could have been discussed already and I might have missed them. If we have them documented already please let us know.

**Comment by rupakraj** [comment]
:+1:

**Comment by prabinraz** [comment]
I agree with you Samundra. It was not discussed prior to putting into the community repo. We can remove it from here and add to my repo and start working there. 

Still I tried to provide some README information. Database file elims.sql added with updated users and ditricts. Please also refer to Readme file for credentials(testusers).

**Comment by samundra** [comment]
Thanks Prabin bro,

I am updating installations instruction once you finish pushing the changes
I will update the readme.

On Mon, Feb 29, 2016 at 7:16 PM, Prabin notifications@github.com wrote:

> I agree with you Samudra. It was not discussed prior to putting into the
> community repo. We can remove it from here and add to my repo and start
> working there.
> 
> Still I tried to provide some README information. Database file elims.sql
> added with updated users and ditricts. Please also refer to Readme file for
> credentials(testusers).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/foss-np/elibrary-IMS/issues/2#issuecomment-190212235.

## 

With best regards,
Samundra Shrestha
http://www.samundra.com.np
Mobile: +977-9851236069
